# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177rhoci0_QbEkmyFn39Hp2rbYH_cIKmW
"""

def kasallik_tashxisi(belgi):
  if belgi=="istima":
      return "Parastamol iching"
  elif belgi == "bosh og'rig'i":
      return "Trimol iching"
  elif belgi =="tish og'rig'i":
      return "Kupen iching"
  elif belgi =="bo'yin og'rig'i":
      return "bolnol maz"
  elif belgi =="ko'z og'ri'gi":
      return "peraksip tomizgich"
  elif belgi =="imunitet tanqisligi":
      return " abikaver dori"
  elif belgi =="qorin og'rig'iga":
      return "tetrasklin"
  else:
      return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)